### ISSUE TITLE
Persistência de estado

### ISSUE THREAD

**Issue by jhonatan-rosario** [pedrolemoz/asp_example#1]
Muito bom o seu exemplo utilizando o atomic state pattern.
Como ficaria a persistência do estado de usuário logado em algum banco NoSQL como o Objectbox, Isar, Realm...?

**Comment by pedrolemoz** [comment]
Olá, @jhonatan-rosario.

Idealmente, a camada de persistência de dados deve ser desacoplada da camada de interface do usuário. Este exemplo cobre apenas a simulação de um sistema de autenticação simples, pois o maior objetivo aqui é validar o Atomic State Pattern em um cenário mais realista. Entretanto, você poderá observar que os reducers possuem o [`AuthenticationService`](https://github.com/pedrolemoz/asp_example/blob/master/lib/app/modules/authentication/services/authentication_service.dart) como dependência em seus construtores. Assim, toda a lógica relacionada à camadas externas, como bancos de dados, APIs e SDKs de terceiros (como o Firebase, por exemplo) são isolados da camada de apresentação.

Note que este serviço de autenticação é apenas uma simulação. Primeiro, é realizada uma validação inicial dos dados de entrada, que são recebidos por meio de um DTO. Para simular uma requisição HTTP, inseri um delay de 1 segundo na execução das funções. Você poderia facilmente substituir este código por uma outra implementação que fizesse uma requisição HTTP real, com os pacotes [`http`](https://pub.dev/packages/http), [`dio`](https://pub.dev/packages/dio), [`uno`](https://pub.dev/packages/uno), ou até mesmo com o cliente padrão do [`dart:io`](https://api.flutter.dev/flutter/dart-io/HttpClient-class.html).

Assim sendo, a persistência de dados em um banco NoSQL como os que você citou também seguiriam uma estrutura semelhante. Você poderia criar um serviço chamado `DataBaseService` que abstraísse o funcionamento das bases de dados para a sua aplicação. De modo geral, você precisaria criar métodos para salvar, recuperar, deletar e verificar a existência dos dados. Daí, o seu reducer poderia consumir esse serviço conforme a necessidade.

Entretanto, o que eu recomendo é que você utilize abstrações, e que crie mais componentes intermediários ao invés de efetuar todas as operações na base de dados. Veja a arquitetura limpa, por exemplo. Lá, há um caso de uso que encapsula regras de negócio, uma infraestrutura que lida com múltiplas fontes de dados e uma camada extra que interage com o mundo externo. O reducer consumiria o caso de uso.

**Comment by jhonatan-rosario** [comment]
Obrigado pelo retorno. Já estou tentando implementar a persistência de dados usando a arquitetura limpa.
